services:
  app:
    image: bekezhan999/software-engineering:lab9
    ports:
      - "8080:8080"
    depends_on:
      - db-main
      - db-test
    environment:
      SPRING_PROFILES_ACTIVE: main

  db-main:
    image: postgres:16
    environment:
      POSTGRES_DB: lab9
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234

  db-test:
    image: postgres:16
    environment:
      POSTGRES_DB: lab9test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
